accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

from django.contrib.auth import urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pages.urls")),
    path("tasks/", include("tasks.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
]

pages/urls.py
from django.urls import path
from .views import HomePageView, AboutPageView

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("about/", AboutPageView.as_view(), name="about"),
]

tasks/urls.py
from django.urls import path
from .views import ListView, CreateView, UpdateView, DeleteView, DetailView

urlpatterns = [
    path("", ListView.as_view(), name="tasks"),
    path("create/", CreateView.as_view(), name="new"),
    path("update/<int:pk>", UpdateView.as_view(), name="edit"),
    path("delete/<int:pk>", DeleteView.as_view(), name="delete"),
    path("detail/<int:pk>", DetailView.as_view(), name="detail"),
]

accounts/models.py
from django.db import models

# Create your models here.

pages/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.db import models
#from django.contrib.auth import get_user_model


class Task(models.Model):
    name = models.CharField(max_length=128)
    description = models.CharField(max_length=256)
    
    class Progress(models.IntegerChoices):
        TODO = 0, ("To Do")
        INPROGRESS = 1, ("In Progress")
        DONE = 2, ("Done")
        
    progress = models.IntegerField(
        choices=Progress.choices,
        default=Progress.TODO,
    )
    def __str__(self):
        return self.name
 

accounts/views.py
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

class SignUpView(CreateView):
    template_name = "registration/signup.html"
    form_class = UserCreationForm
    success_url = reverse_lazy("login")

pages/views.py
from django.views.generic import TemplateView

class HomePageView(TemplateView):
    template_name = "pages/home.html"

class AboutPageView(TemplateView):
    template_name = "pages/about.html"

# Create your views here.

tasks/views.py
from django.shortcuts import render
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from .models import Task
from django.urls import reverse_lazy
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
)
# Create your views here.
class ListView(ListView):
    template_name = "tasks/list.html"
    model = Task

class DetailView(DetailView):
    template_name = "tasks/detail.html"
    model = Task

class CreateView(LoginRequiredMixin, CreateView):
    template_name = "tasks/create.html"
    model = Task
    fields = ["name", "description", "progress"]
    success_url = reverse_lazy("tasks")
    
class UpdateView(LoginRequiredMixin, UpdateView):
    template_name = "tasks/edit.html"
    model = Task
    fields = ["name", "description", "progress"]
    success_url = reverse_lazy("tasks")
    
class DeleteView(LoginRequiredMixin, DeleteView):
    template_name = "tasks/delete.html"
    model = Task
    success_url = reverse_lazy("tasks")

    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link 
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" 
        rel="stylesheet" 
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" 
        crossorigin="anonymous">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">Issue Manager</a>
            <a class="navbar-brand" href="{% url 'about' %}">About</a>
            <a class="navbar-brand" href="{% url 'tasks' %}">Tasks</a>
            <a class="navbar-brand" href="{% url 'new' %}">Create</a>
            <button class="navbar-toggler" 
                type="button" data-bs-toggle="collapse" 
                data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" 
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            </div>
        </div>
    </nav>
    {% block content %}{% endblock content %}
    <script 
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" 
        crossorigin="anonymous">

templates/pages/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}About Us{% endblock title %}

{% block content %}
<h1>About Me</h1>
<p>Lorem ipsum dolor sit amet</p>
{% endblock content %}

templates/pages/home.html
{% extends 'base.html' %}


{% block title %}Home{% endblock title%}

{% block content %}
<h1>Home</h1>
<p>Welcome to my Issue Manager... where the issues keep coming</p>
{% endblock content %}

templates/tasks/create.html
{% extends 'base.html' %}


{% block title %}New Task{% endblock title %}

{% block content %}
<h1>Create New Task</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-success" value="Create">
</form>
{% endblock content %}

templates/tasks/delete.html
{% extends 'base.html' %}


{% block title %}Deleted Task{% endblock title %}

{% block content %}
<h1>Deleted Task</h1>
<p>Are you sure you want to delete "{{ task.name }}"?</p>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-danger" value="Confirm">
</form>
{% endblock content %}

templates/tasks/detail.html
{% extends 'base.html' %}


{% block title %}{{ task.name }}{% endblock title %}

{% block content %}
<h1>{{ task.name }}</h1>
<h3>{{ task.get_progress_display }}</h3>
<p>{{ task.description }}</p>
<a href="{% url 'edit' task.id %}">edit</a>
<a href="{% url 'delete' task.id %}">delete</a>
{% endblock content %}

templates/tasks/edit.html
{% extends 'base.html' %}


{% block title %}Edit Task{% endblock title %}

{% block content %}
<h1>Edit Task</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-warning" value="Edit">
</form>
{% endblock content %}

templates/tasks/list.html
{% extends 'base.html' %}

{% block title %}Tasks{% endblock title %}



{% block content%}
<h1>Tasks</h1>

    {% for task in task_list %}
    <div class="task-card">
        <div class="card-body">
        <h5 class="card-title">{{ task.name }}</h5>
        <p class="card-text">{{ task.get_progress_display }}</p>
        <p class="card-body">{{ task.description }}</p>
        <a href="{% url 'detail' task.id %}">
            {{ task.name }}
        </div>
    </a>
    {% endfor %}

{% endblock content %}